import { Destination, ParkingSession, User } from './types';

export const MOCK_USER: User = {
  id: 'u_123',
  points: 1540,
  username: 'SarahPark',
  usernameNormalized: 'sarahpark',
  privacyMode: 'public',
  createdAt: '2026-01-15T10:30:00Z',
};

export const MOCK_HISTORY: ParkingSession[] = [
  {
    id: 'ps_1',
    userId: 'usr_1',
    latitude: -33.9321,
    longitude: 18.8602,
    locationName: 'Stellenbosch University (Neelsie)',
    startedAt: '2026-08-24T10:15:00Z',
    endedAt: '2026-08-24T11:45:00Z',
    estimatedDuration: '2 hours',
    status: 'completed',
    pointsAwarded: 10,
  },
  {
    id: 'ps_2',
    userId: 'usr_1',
    latitude: -33.9015,
    longitude: 18.4186,
    locationName: 'Waterfront Victoria Wharf',
    startedAt: '2026-08-23T14:30:00Z',
    endedAt: '2026-08-23T15:05:00Z',
    estimatedDuration: '30 min',
    status: 'completed',
    pointsAwarded: 10,
  },
  {
    id: 'ps_3',
    userId: 'usr_1',
    latitude: -34.0841,
    longitude: 18.8234,
    locationName: 'Somerset Mall Main Entrance',
    startedAt: '2026-08-22T09:00:00Z',
    endedAt: '2026-08-22T09:20:00Z',
    estimatedDuration: '15 min',
    status: 'completed',
    pointsAwarded: 10,
  },
  {
    id: 'ps_4',
    userId: 'usr_1',
    latitude: -33.9285,
    longitude: 18.8654,
    locationName: 'Stellenbosch Engineering Faculty',
    startedAt: '2026-08-20T12:00:00Z',
    endedAt: '2026-08-20T15:15:00Z',
    estimatedDuration: '3+ hours',
    status: 'completed',
    pointsAwarded: 10,
  }
];

export const MOCK_DESTINATIONS: Destination[] = [
  {
    id: 'dest_1',
    name: 'Stellenbosch University',
    latitude: -33.9321,
    longitude: 18.8602,
    zones: [
      {
        id: 'z_1_1',
        name: 'Neelsie Student Centre Parking',
        latitude: -33.9321,
        longitude: 18.8602,
        radius: 65,
        likelihoodScore: 25,
        likelihoodStatus: 'low',
      },
      {
        id: 'z_1_2',
        name: 'Ryneveld Street Parking Zone',
        latitude: -33.9312,
        longitude: 18.8582,
        radius: 80,
        likelihoodScore: 55,
        likelihoodStatus: 'moderate',
      },
      {
        id: 'z_1_3',
        name: 'Coetzenburg Sports Fields Lot',
        latitude: -33.9362,
        longitude: 18.8672,
        radius: 120,
        likelihoodScore: 85,
        likelihoodStatus: 'high',
      },
    ],
  },
  {
    id: 'dest_2',
    name: 'Waterfront Victoria Wharf',
    latitude: -33.9015,
    longitude: 18.4186,
    zones: [
      {
        id: 'z_2_1',
        name: 'Main Underground Parking Garage',
        latitude: -33.9015,
        longitude: 18.4186,
        radius: 75,
        likelihoodScore: 15,
        likelihoodStatus: 'low',
      },
      {
        id: 'z_2_2',
        name: 'Breakwater Boulevard Open Lot',
        latitude: -33.9032,
        longitude: 18.4208,
        radius: 95,
        likelihoodScore: 60,
        likelihoodStatus: 'moderate',
      },
      {
        id: 'z_2_3',
        name: 'Granger Bay Parking Deck',
        latitude: -33.8995,
        longitude: 18.4231,
        radius: 110,
        likelihoodScore: 90,
        likelihoodStatus: 'high',
      },
    ],
  },
  {
    id: 'dest_3',
    name: 'Somerset Mall',
    latitude: -34.0841,
    longitude: 18.8234,
    zones: [
      {
        id: 'z_3_1',
        name: 'Cinema Entrance Parking',
        latitude: -34.0841,
        longitude: 18.8234,
        radius: 70,
        likelihoodScore: 35,
        likelihoodStatus: 'low',
      },
      {
        id: 'z_3_2',
        name: 'Food Court Parking Deck',
        latitude: -34.0825,
        longitude: 18.8252,
        radius: 90,
        likelihoodScore: 50,
        likelihoodStatus: 'moderate',
      },
      {
        id: 'z_3_3',
        name: 'Overflow Parking Lot C',
        latitude: -34.0862,
        longitude: 18.8211,
        radius: 130,
        likelihoodScore: 95,
        likelihoodStatus: 'high',
      },
    ],
  },
  {
    id: 'dest_4',
    name: 'Durbanville Hills Wine Estate',
    latitude: -33.8248,
    longitude: 18.5665,
    zones: [
      {
        id: 'z_4_1',
        name: 'Tasting Room Main Lot',
        latitude: -33.8248,
        longitude: 18.5665,
        radius: 60,
        likelihoodScore: 45,
        likelihoodStatus: 'moderate',
      },
      {
        id: 'z_4_2',
        name: 'Lower Restaurant Lot',
        latitude: -33.8262,
        longitude: 18.5678,
        radius: 80,
        likelihoodScore: 80,
        likelihoodStatus: 'high',
      },
    ],
  },
];

export const MOCK_USER_CURRENT_LOCATION = {
  latitude: -33.9333,
  longitude: 18.8579,
  name: 'Andringa Street, Stellenbosch (Your Location)',
};
